# Data, Models, and Logs
data/
logs/
*.csv
*.log
```


# FOR LOCAL DEVELOPMENT
BINANCE_API_KEY="XTa9VqCM638Cpqw79eqxAhlxtdkyhXheHK8w0Q6N7O2Cv76sNLLi2TsIwsmoyzYL"
BINANCE_API_SECRET="83CAql4PfEVdFDJPkbBuDITTPxpRU61EBMPqsIfiDl6maN34UJRNGARPHQEmFDXE"
FINNHUB_API_KEY="d4gacohr01qm5b34m070d4gacohr01qm5b34m07g"

# For PostgreSQL Database Connection 
[connections.postgresql]
dialect = "postgresql"
host = "ep-shy-water-a7fcme0j-pooler.ap-southeast-2.aws.neon.tech"
database = "neondb"
username = "neondb_owner"
password = "npg_b9XPkCZpUhn2"
port = "5432"
sslmode = "require"